config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root to: 'dashboard#index'
  resources :users
  resources :songs
  resources :recordings
  resources :comments
  resources :dashboard, only: :index
  resources :thesaurus

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true
  belongs_to :recording
  belongs_to :song
  belongs_to :user

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
end

app/models/lyric.rb
class Lyric < ActiveRecord::Base
end

app/models/recording.rb
class Recording < ActiveRecord::Base
  acts_as_commentable
  belongs_to :song
  has_many :comments, foreign_key: 'commentable_id'
  has_many :user_recordings
  has_many :users, through: :user_recording
  validates :name, presence: true
  mount_uploader :file, FileUploader
end

app/models/song.rb
class Song < ActiveRecord::Base
  require 'carrierwave'
  acts_as_commentable
  belongs_to :user_song
  has_many :recordings
  has_many :comments, foreign_key: 'commentable_id'

end

app/models/user.rb
require 'digest/md5'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, uniqueness: true,
            format: { with: /\A[a-zA-Z0-9]+\z/,
            message: "username can only contain letters and numbers"}

  has_many :user_songs
  has_many :songs, through: :user_songs
  has_many :user_recordings
  has_many :recordings, through: :user_recordings
  has_many :comments

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)",
      { :value => login }]).first
    else
      where(conditions).first
    end
  end
end

app/models/user_recording.rb
class UserRecording < ActiveRecord::Base
  acts_as_commentable
  belongs_to :user
  belongs_to :recording
end

app/models/user_song.rb
class UserSong < ActiveRecord::Base
  acts_as_commentable

  belongs_to :user
  belongs_to :song
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  	@comments = Comment.all
  end

  def new
  	@comment = Comment.new
  end

  def create
    @user = current_user
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash[:notice] = "Your comment has been created"
      redirect_to song_path(@comment.commentable_id)
    else
      flash[:alert] = "Your comment could not be created"
      redirect_to song_path(@comment.commentable_id)
    end
  end

  def show
    # @user = User.find(params[:id])
  	@comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :authenticity_token, :username, :recording_id, :song_id, :comment, :commentable_id, :commentable_type, :user_id)
  end
end
#<Comment id: nil, title: "", comment: "something about something", commentable_id: 31, commentable_type: nil, user_id: nil, role: "comments", created_at: nil, updated_at: nil>
# 2.1.1 :008 > comment

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @songs = Song.all
    @recordings = Recording.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/lyric_controller.rb
class LyricController < ApplicationController
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController

  def new
    @recording = Recording.new
  end

  def index
    @recordings = Recording.all
  end

  def create
    @recording = current_user.recordings.build(recording_params)
    if @recording.save
      redirect_to song_path(@recording.song_id), notice: "Your recording has been created!"
    else
      flash[:alert] = "Your recording could not be created."
      redirect_to song_path(@recording.song_id)
    end
  end

  def show
    @recording = Recording.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  private

  def recording_params
    params.require(:recording).permit(:name, :file, :comment, :song_id, :play_count, :created_at)
  end
end

app/controllers/songs_controller.rb
class SongsController < UsersController
  skip_before_filter :require_profile!, only: :edit

  def new
    @song = Song.new
  end

  def index
    @songs = Song.all
  end

  def create
    @song = current_user.songs.build(song_params)
    if @song.save
      redirect_to song_path(@song.id), notice: "Your song has been created!"
    else
      flash[:alert] = @song.save ? "Your song could not be created." : "Your squmbl could not be saved."
      render :new
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find_by_id(params[:id])
    if @song.update(lyric: params[:song][:lyric], title: params[:song][:title], writers: params[:song][:writers])
      redirect_to song_path(@song.id), notice: "Your song has been updated!"
    else
      flash[:alert] = @song.published ? "Your song could not be created." : "Your song could not be saved."
      render :new
    end
  end

  private
  def song_params
    params.require(:song).permit(:title, :user_id, :lyric, :writers, :recording, :comment, :edit)
  end
end

app/controllers/thesaurus_controller.rb
class ThesaurusController < ApplicationController
  require "dinosaurus"

  def index
    @results = Dinosaurus.lookup(params[:q])
    @word = params[:q]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lyric_helper.rb
module LyricHelper
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/helpers/thesaurus_helper.rb
module ThesaurusHelper
end

app/views/home/index.html.haml
#user
  .user_dash.margin_auto.text_center
    %p #{current_user.username.upcase}'s working songs #{current_user.last_name} #{current_user.last_name} #{current_user.phone} #{current_user.email}
    #songs
      %h1 Songs
      - @songs.each do |song|
        .button= link_to song.title, song_path(song.id)
    .create_song.left
      = render "shared/song_form"

app/views/songs/edit.html.haml
= render partial: "shared/edit_song_form"

app/views/songs/index.html.haml
  #user
  .user_dash.margin_auto.text_center
    %p #{current_user.username.upcase}'s working songs #{current_user.last_name} #{current_user.last_name} #{current_user.phone} #{current_user.email}
    #songs
      %h1 Songs
      - @songs.each do |song|
        .button= link_to song.title, song_path(song.id)
    .create_song.left
      = render "shared/song_form"

app/views/songs/show.html.haml
.nudge
.nudge
#user_dash.text_center
  %p #{current_user.username.upcase}'s working song #{current_user.last_name} #{current_user.last_name} #{current_user.phone} #{current_user.email}
.space
.bump
.bump
.sectionWrapper.margin_left
  %h3= @song.title
  .button= link_to "Edit song", edit_song_path(@song)
  %p= @song.writers
  = render partial: "shared/edit_lyric_form"
  = render partial: "shared/comment_form"
  #comment_show
  - @song.comments.each do |comment|
    - if comment.commentable_type == "Songs"
      %strong
        = simple_format(comment.comment)
        <br>
        Posted by #{comment.username} #{time_ago_in_words(comment.created_at)} ago.
      <br>
      <br>
#recordings.sectionWrapper.right.margin_right
  %h3 Add recording
  #recording_form
  = render partial: "shared/recording_form"
  %h3 Recordings booty
  #recordings_index
  - @song.recordings.each do |recording|
    %p= recording.name
    <audio controls="controls">
    <source src="#{recording.file_url}" type="audio/mp3">
    <source src="#{recording.file_url}" type="audio/mpeg">
    Your browser does not support the audio element.
    </audio>
    .song
    = render partial: "shared/rec_comment_form", locals: {recording: recording}
    %small #{recording.created_at}
    %h4 Comments:
    #comment_show booty
    - @song.comments.each do |comment|
      - if comment.commentable_type == "Recording" && comment.title == recording.name
        %strong
          = simple_format(comment.comment)
          <br>
          Posted by #{comment.username} #{time_ago_in_words(comment.created_at)} ago.
          <br>
          <br>
.bump
.largeSectionWrapper.lyric.margin_left
  %h3= @song.title
  .button= link_to "Edit song", edit_song_path(@song)
  %p= @song.writers
  = simple_format(@song.lyric)

app/views/thesaurus/index.html.haml
.space
.space

.sectionWrapper.margin_left
  = form_tag("/thesaurus", method: "get") do
    = text_field_tag(:q)
    = submit_tag("Thesaurus")
  .contentWrapper
    %form{action: "javascript:RhymeBrainSubmit()"}
      %input#RhymeBrainInput{type: "text"}/
      %input{type: "submit", value: "Rhyme"}/
      :javascript
        var RhymeBrainMaxResults = 50;
      %script{src: "http://rhymebrain.com/external.js", type: "text/javascript"}
  .sectionWrapper.text_center
  - @results.each do |key, value|
    -value.each do |k,v|
      <br />
      - if @word
        %h1 #{@word.downcase}
        <br />
        #keys #{key}: #{k}:
        <br /><br />
        - v.each do |val|
          #values #{val},

app/views/users/shared/_links.haml
- if controller_name != 'sessions'
  = link_to "Sign in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/

app/views/users/show.html.haml
      #user
        %h1 User
        %p #{current_user.first_name} #{current_user.last_name}
        %p= current_user.username
        %p= current_user.phone
        %p= current_user.email

      #songs
        %h1 Songs
        - current_user.songs.each do |song|
          %p= song.title
          -# %p= song.comment