config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root to: 'dashboard#index'
  resources :users
  resources :songs
  resources :recordings
  resources :comments
  resources :dashboard, only: :index
  resources :thesaurus

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true
  belongs_to :recording
  belongs_to :song
  belongs_to :user

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
end

app/models/lyric.rb
class Lyric < ActiveRecord::Base
end

app/models/recording.rb
class Recording < ActiveRecord::Base
  acts_as_commentable
  belongs_to :song
  has_many :comments, foreign_key: 'commentable_id'
  has_many :user_recordings
  has_many :users, through: :user_recording
  validates :name, presence: true
  mount_uploader :file, FileUploader
end

app/models/song.rb
class Song < ActiveRecord::Base
  require 'carrierwave'
  acts_as_commentable
  belongs_to :user_song
  has_many :recordings
  has_many :comments, foreign_key: 'commentable_id'

end

app/models/user.rb
require 'digest/md5'
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, uniqueness: true,
            format: { with: /\A[a-zA-Z0-9]+\z/,
            message: "username can only contain letters and numbers"}

  has_many :user_songs
  has_many :songs, through: :user_songs
  has_many :user_recordings
  has_many :recordings, through: :user_recordings
  has_many :comments

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value OR lower(email) = lower(:value)",
      { :value => login }]).first
    else
      where(conditions).first
    end
  end
end

app/models/user_recording.rb
class UserRecording < ActiveRecord::Base
  acts_as_commentable
  belongs_to :user
  belongs_to :recording
end

app/models/user_song.rb
class UserSong < ActiveRecord::Base
  acts_as_commentable

  belongs_to :user
  belongs_to :song
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  	@comments = Comment.all
  end

  def new
  	@comment = Comment.new
  end

  def create
    @user = current_user
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      flash[:notice] = "Your comment has been created"
      redirect_to song_path(@comment.commentable_id)
    else
      flash[:alert] = "Your comment could not be created"
      redirect_to song_path(@comment.commentable_id)
    end
  end

  def show
    # @user = User.find(params[:id])
  	@comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :authenticity_token, :username, :recording_id, :song_id, :comment, :commentable_id, :commentable_type, :user_id)
  end
end
#<Comment id: nil, title: "", comment: "something about something", commentable_id: 31, commentable_type: nil, user_id: nil, role: "comments", created_at: nil, updated_at: nil>
# 2.1.1 :008 > comment

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @users = User.all
    @user = current_user
    @songs = Song.all
    @recordings = Recording.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/lyric_controller.rb
class LyricController < ApplicationController
end

app/controllers/songs_controller.rb
class SongsController < UsersController
  skip_before_filter :require_profile!, only: :edit

  def new
    @song = Song.new
  end

  def index
    @songs = Song.all
  end

  def create
    @song = current_user.songs.build(song_params)
    if @song.save
      redirect_to song_path(@song.id), notice: "Your song has been created!"
    else
      flash[:alert] = @song.save ? "Your song could not be created." : "Your squmbl could not be saved."
      render :new
    end
  end

  def show
    @song = Song.find(params[:id])
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find_by_id(params[:id])
    if @song.update(lyric: params[:song][:lyric], title: params[:song][:title], writers: params[:song][:writers])
      redirect_to song_path(@song.id), notice: "Your song has been updated!"
    else
      flash[:alert] = @song.published ? "Your song could not be created." : "Your song could not be saved."
      render :new
    end
  end

  private
  def song_params
    params.require(:song).permit(:title, :user_id, :lyric, :writers, :recording, :comment, :edit)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lyric_helper.rb
module LyricHelper
end

app/helpers/recordings_helper.rb
module RecordingsHelper
end

app/helpers/thesaurus_helper.rb
module ThesaurusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <title>StraightUpSound</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'reset', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <header class="margin_auto text_center box_shadow">
        <div id="logo">
          <%= image_tag "suslogo.jpg" %>
        </div>
        <ul class="devise_navigation right"></ul>
        <% if user_signed_in? %>
          <div class="nudge"></div>
          <li class="nav navButton right">
            <%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %>
          </li>
        <% else %>
          <li class="nav navButton">
            <%= link_to 'Sign in', new_user_session_path %>
          </li>
        <% end %>
        <ul class="main_navigation left margin_auto">
          <li class="nav navButton">
            <%= link_to 'Dashboard', root_path %>
          </li>
          <li class="nav navButton">
            <%= link_to 'tools', thesaurus_path %>
          </li>
          <li class="nav navButton">
            <%= link_to 'Straight Up Sound', 'http://www.straightupsoundstudio.com' %>
          </li>
        </ul>
      </header>
      <div class="space"></div>
      <div class="big_bump"></div>
      <div class="bump"></div>
      <div class="page_content">
        <div class="flash_alert text_center box_shadow">
          <div class="alert background_color_saffron">
            <%= alert %>
          </div>
          <div class="notice">
            <%= notice %>
          </div>
        </div>
        <%= yield %>
      </div>
      <div class="middle box_shadow"></div>
      <div class="middle_content"></div>
      <div class="middle box_shadow"></div>
      <div class="third_content"></div>
      <div class="middle box_shadow"></div>
      <div class="fourth_content"></div>
    </div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title StraightUpSound
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'reset', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %header.margin_auto.text_center.box_shadow
        #logo=image_tag "suslogo.jpg"
        %ul.devise_navigation.right
        - if user_signed_in?
          .nudge
          %li.nav.navButton.right= link_to 'Sign out', destroy_user_session_path, method: 'delete'
        - else
          %li.nav.navButton= link_to 'Sign in', new_user_session_path
        %ul.main_navigation.left.margin_auto
          %li.nav.navButton= link_to 'dashboard', root_path
          %li.nav.navButton= link_to 'tools', thesaurus_path
          %li.nav.navButton= link_to 'Straight Up Sound', 'http://www.straightupsoundstudio.com'
      .space
      .big_bump
      .bump
      .page_content
        .flash_alert.text_center.box_shadow
          .alert.background_color_saffron= alert
          .notice= notice
        = yield
      .middle.box_shadow
      .middle_content
      .middle.box_shadow
      .third_content
      .middle.box_shadow
      .fourth_content

app/views/shared/_comment_form.haml
#song_comment_form
  =simple_form_for Comment.new, :method => :post do |f|
    =f.input :comment, as: :text, :input_html => {:size => "38x2"}, label: false
    =f.input :commentable_type, :as => :hidden, :input_html => {:value => "Songs"}
    =f.input :username, :as => :hidden, :input_html => {:value => "#{current_user.username}"}
    =f.input :commentable_id, :as => :hidden, :input_html => {:value => @song.id}
    =f.submit "make comment"

app/views/shared/_comments.html.haml
= div_for(comment) do
  %p
    %strong
      posted #{time_ago_in_words(comment.created_at)} ago
    = h(comment.body)

app/views/shared/_edit_lyric_form.haml
#edit_lyric.margin_left
  =simple_form_for @song do |f|
    =f.input :song_id, :as => :hidden, :input_html => {:value => @song.id}
    =f.input :writers, :as=> :hidden, :input_html => {:value =>@song.writers}
    =f.input :title, :as=> :hidden, :input_html => {:value =>@song.title}
    =f.input :lyric, :as => :text, :input_html => {:size => "36x23"}, label: false, placeholder: "lyric"
    =f.submit "edit song"

app/views/shared/_edit_song_form.haml
.space
.sectionWrapper.large_marge_left
  #edit_song
    =simple_form_for @song do |f|
      %p edit song
      =f.input :title, label: false, placeholder: "title", :input_html => {:maxlength =>55,:style=> 'width: 245px'}
      =f.input :writers, label: false, placeholder: "writers", :input_html => {:maxlength =>55,:style=> 'width: 245px'}
      =f.input :lyric, :as => :text, :input_html => {:size => "36x23"}, label: false, placeholder: "lyric"
      =f.submit "edit song"

app/views/shared/_rec_comment_form.haml
#recording_comment_form
  =simple_form_for Comment.new, :method => :post do |f|
    =f.input :comment, as: :text, :input_html => {:size => "38x2"}, label: false
    =f.input :commentable_type, :as => :hidden, :input_html => {:value => "Recording"}
    =f.input :commentable_id, :as => :hidden, :input_html => {:value => @song.id}
    =f.input :title, :as => :hidden, :input_html => {:value => recording.name}
    =f.input :user_id, :as => :hidden, :input_html => {:value => @song.id}
    =f.submit "make comment"

app/views/shared/_recording_form.haml
#recording_form
  =simple_form_for Recording.new, :html => { :multipart => true }do |f|
    =f.input :name, :required => true, label: false, :input_html => {:size => "38x2"}, placeholder: "name"
    =f.label "file"
    =f.file_field :file, :input_html => {:label => "File"}
    =f.input :song_id, :as => :hidden, :input_html => {:value => @song.id}
    =f.submit "create recording"

app/views/shared/_song_form.haml
.song
  =simple_form_for Song.new do |f|
    %h3 Create song
    =f.input :title, label: false, placeholder: "title", :input_html => {:maxlength =>55,:style=> 'width: 245px'}
    =f.input :writers, label: false, placeholder: "writers", :input_html => {:maxlength =>55,:style=> 'width: 245px'}
    =f.input :lyric, :as => :text, :input_html => {:size => "36x23"}, label: false, placeholder: "lyric"
    =f.input :commentable_id, :as => :hidden, :input_html => {:value => current_user.id}
    =f.submit "create song"